apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kuboard-data-pvc
  namespace: {{ .Release.Namespace | quote }}
spec:
  {{- if .Values.Storage.KuboardStorageClass }}
  storageClassName: {{ .Values.Storage.KuboardStorageClass | quote }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
