apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-kuboard-etcd
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ClusterIP
  ports:
  - port: 2379
    name: client
  - port: 2380
    name: peer
  selector:
    app: {{ .Release.Name }}-kuboard-etcd
