apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-kuboard-etcd
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ .Release.Name }}-kuboard-etcd
spec:
  serviceName: {{ .Release.Name }}-kuboard-etcd
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kuboard-etcd
  template:
    metadata:
      name: {{ .Release.Name }}-kuboard-etcd
      labels:
        app: {{ .Release.Name }}-kuboard-etcd
    spec:
      containers:
      - name: kuboard-etcd
        image: {{ .Values.Config.EtcdImage | quote }}
        ports:
        - containerPort: 2379
          name: client
        - containerPort: 2380
          name: peer
        env:
        - name: KUBOARD_ETCD_ENDPOINTS
          value: >-
            {{ .Release.Name }}-kuboard-etcd-0.{{ .Release.Name }}-kuboard-etcd:2379,{{ .Release.Name }}-kuboard-etcd-1.{{ .Release.Name }}-kuboard-etcd:2379,{{ .Release.Name }}-kuboard-etcd-2.{{ .Release.Name }}-kuboard-etcd:2379
        volumeMounts:
        - name: {{ .Release.Name }}-data
          mountPath: /data
        command:
          - /bin/sh
          - -c
          - |
            PEERS="{{ .Release.Name }}-kuboard-etcd-0=http://{{ .Release.Name }}-kuboard-etcd-0.{{ .Release.Name }}-kuboard-etcd:2380,{{ .Release.Name }}-kuboard-etcd-1=http://{{ .Release.Name }}-kuboard-etcd-1.{{ .Release.Name }}-kuboard-etcd:2380,{{ .Release.Name }}-kuboard-etcd-2=http://{{ .Release.Name }}-kuboard-etcd-2.{{ .Release.Name }}-kuboard-etcd:2380"
            exec etcd --name ${HOSTNAME} \
              --listen-peer-urls http://0.0.0.0:2380 \
              --listen-client-urls http://0.0.0.0:2379 \
              --advertise-client-urls http://${HOSTNAME}.{{ .Release.Name }}-kuboard-etcd:2379 \
              --initial-advertise-peer-urls http://${HOSTNAME}:2380 \
              --initial-cluster-token kuboard-etcd-cluster-1 \
              --initial-cluster ${PEERS} \
              --initial-cluster-state new \
              --data-dir /data/kuboard.etcd
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      {{- if .Values.Storage.EtcdStorageClass }}
      storageClassName: {{ .Values.Storage.EtcdStorageClass | quote }}
      {{- end }}
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi
